services:
  bot:
    build: .
    restart: unless-stopped

  database:
    image: mariadb:latest
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - databasedata:/var/lib/mysql

volumes:
  databasedata: # guh
