CREATE TABLE IF NOT EXISTS economy (
	user_id VARCHAR(26) NOT NULL,
	balance INTEGER DEFAULT 0,
	bank INTEGER DEFAULT 0,
	PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS cooldowns(
	user_id VARCHAR(26) NOT NULL,
	work INTEGER DEFAULT 0,
	steal INTEGER DEFAULT 0,
	hourly INTEGER DEFAULT 0,
	daily INTEGER DEFAULT 0,
	FOREIGN KEY (user_id) REFERENCES economy(user_id)
);
